[font]
size = 13

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
y = 2

[window]
decorations = "none"
opacity = 0.96
startup_mode = "Maximized"

[window.padding]
x = 8
y = 8

# Color below sourced (albeit altered) from:
#   TokyoNight Alacritty Colors
#   Theme: Tokyo Night
#   Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_night.toml
[colors.primary]
background = "#010402"
foreground = '#e6e9f5'

[colors.cursor]
cursor = '#c0caf5'
text = '#1a1b26'

[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
